server:
  port: 8082
spring:
  application:
    name: application-log
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.90.125:8761/eureka/
logging:
  file:
    path: ./../webapps/logback-test/logs/
